name: shapley_effects

channels:
- conda-forge
- opensourceeconomics

dependencies:
- python
- numpoly==1.0.8
- ipython
- scipy=1.6.1
- numpy
- numba
- pandas
- jupyterlab
- matplotlib
- seaborn
- pytest
- chaospy
- pip
- pip:
     - C:\Users\admin\Masterarbeit\econsa
#     - flake8
#     - black
#     - pre-commit

